### ISSUE TITLE
nable to run the code

### ISSUE THREAD

**Issue by Dionysus7777777** [DENG-MIT/Biomass.jl#5]
Hello, we are very interested in your work and have tried running your code, but we encountered some issues. You mentioned in another repository that it is best to use Julia 1.6, is that the case for this repository as well? Additionally, are there any specific dependency versions required? I am currently unable to run your code, and I am not sure if it's an environment issue or a mistake on my part. Could you please explain which parts of the code I should run step by step? I haven't been able to find a practical README file to understand these basic details.Additionally, I found a file named CRNN-biomass-python-main. May I ask if this file can be used interchangeably with the Julia file? It seems to me that the Python file contains very little content.

**Comment by jiweiqi** [comment]
Hi @Dionysus7777777 , thanks for your interests. Looks like what you are facing is due to environments or dependency issues. I don't have the original environments I used at hands. I'd recommend consulting Julia documents and Code Assistance like ChatGPT to adapt the code to the Julia/package versions you are using.

You shall start from this file https://github.com/DENG-MIT/Biomass.jl/blob/main/src/crnn_cellulose.jl, which is the main program.

I don't recall if that python version works or not. I'd recommend working with the Julia version.

**Comment by Dionysus7777777** [comment]
Thank you very much for your response. I may need to trouble you again during future learning.
